name: Continuous Integration Git Hub Actions

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login para Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ vars.DOCKER_PASSWORD }}
    
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'
        cache: maven
        
    - name: Build application jar
      working-directory: idealize
      run: mvn clean package

    - name: Docker compose build
      working-directory: Downloads/idealize
      run: docker compose build

    - name: Docker compose build
      run: |
        docker tag ${{ vars.DOCKER_USERNAME }}/idealize:latest ${{ vars.DOCKER_USERNAME }}/idealize:${{ github.run_id }}
        
        docker push ${{ vars.DOCKER_USERNAME }}/idealize:${{ github.run_id }}
        docker push ${{ vars.DOCKER_USERNAME }}/idealize:latest
